package com.data_management;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;

/**
 * Reads patient data from text files generated by the file output strategy.
 */
public class FileDataReader implements DataReader {
    private static final Pattern LINE_PATTERN = Pattern.compile(
            "Patient ID:\\s*(\\d+),\\s*Timestamp:\\s*(\\d+),\\s*Label:\\s*([^,]+),\\s*Data:\\s*(.+)");
    private final Path inputDirectory;

    public FileDataReader(String inputDirectory) {
        this.inputDirectory = Paths.get(inputDirectory);
    }

    @Override
    public void readData(DataStorage dataStorage) throws IOException {
        if (!Files.exists(inputDirectory) || !Files.isDirectory(inputDirectory)) {
            throw new IOException("Input path is not a directory: " + inputDirectory.toAbsolutePath());
        }

        try (Stream<Path> files = Files.list(inputDirectory)) {
            files.filter(Files::isRegularFile)
                    .forEach(path -> {
                        try (BufferedReader reader = Files.newBufferedReader(path)) {
                            String line;
                            while ((line = reader.readLine()) != null) {
                                parseLine(line, dataStorage);
                            }
                        } catch (IOException e) {
                            throw new RuntimeException("Error reading file " + path, e);
                        }
                    });
        }
    }

    private void parseLine(String line, DataStorage dataStorage) {
        if (line == null || line.isBlank()) {
            return;
        }

        Matcher matcher = LINE_PATTERN.matcher(line.trim());
        if (!matcher.matches()) {
            return;
        }

        int patientId = Integer.parseInt(matcher.group(1));
        long timestamp = Long.parseLong(matcher.group(2));
        String label = matcher.group(3).trim();
        String rawData = matcher.group(4).trim();

        Double value = parseNumericValue(rawData, label);
        if (value == null) {
            return;
        }

        dataStorage.addPatientData(patientId, value, label, timestamp);
    }

    private Double parseNumericValue(String rawData, String label) {
        if (rawData.endsWith("%")) {
            rawData = rawData.substring(0, rawData.length() - 1).trim();
        }

        if (label.equalsIgnoreCase("Alert")) {
            if (rawData.equalsIgnoreCase("triggered")) {
                return 1.0;
            }
            if (rawData.equalsIgnoreCase("resolved")) {
                return 0.0;
            }
            return null;
        }

        try {
            return Double.parseDouble(rawData);
        } catch (NumberFormatException e) {
            return null;
        }
    }
}
